---
name: Set Up Nodejs
description: Set up Nodejs
inputs:
  node-version:
    description: Node version
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # pin@v4.0.3
      with:
        registry-url: "https://npm.pkg.github.com"
        node-version: ${{ inputs.node-version }}
