---
name: Set Up Nodejs
description: Set up Nodejs
inputs:
  node-version:
    description: Node version
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # pin@v4.1.0
      with:
        registry-url: "https://npm.pkg.github.com"
        node-version: ${{ inputs.node-version }}
