---
name: Set Up Nodejs
description: Set up Nodejs
inputs:
  node-version:
    description: Node version
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # pin@v4.0.1
      with:
        registry-url: "https://npm.pkg.github.com"
        node-version: ${{ inputs.node-version }}
