# TODO
---
name: Transfer Release Asset to AWS S3
description: Transfer release asset to AWS S3
inputs:
  artifact-name:
  release-tag:
  working-directory-terraform:
  working-directory-nodejs:
  terraform-version:
  terraform-nodejs-script:
  terraform-s3-bucket-name-output:
  ACCESS_TOKEN:
runs:
  using: "composite"
  steps:
    # github-branch-event
    - uses: aps831/gh-actions/github-branch-event@master
      id: branch-event
      with:
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}

    # git checkout event branch
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ steps.branch-event.outputs.branch-event }}

    # action-download-release-artifact
    - uses: aps831/gh-actions/action-download-release-artifact@feat/deploy
      id: artifact
      with:
        artifact-name: ${{ inputs.artifact-name }}
        release-tag: ${{ inputs.release-tag }}
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}

    # TODO cleanup
    - shell: bash
      run: |
        echo "Running unzip on ${{ steps.artifact.outputs.artifact-path }}"
        ls -la ${{ steps.artifact.outputs.artifact-path }}
        unzip ${{ steps.artifact.outputs.artifact-path }}

    # TODO cleanup
    - id: artifact-dir
      shell: bash
      run: |
        path=${{ steps.artifact.outputs.artifact-path }}
        artifact_dir="${path%.zip}"
        echo "Calculated artifact directory: $artifact_dir"
        ls -la $artifact_dir
        echo "artifact-dir=$artifact_dir" >> $GITHUB_OUTPUT

    # inject terraform and artifact directory values into script
    - id: script
      shell: bash
      run: |
        script=${{ inputs.terraform-nodejs-script }}
        script=${script/%TERRAFORM_DIR/"${{ inputs.working-directory-terraform }}"}
        script=${script/%ARTIFACT_DIR/"${{ steps.artifact-dir.outputs.artifact-dir }}"}
        echo "Updated script with Terraform and artifact directories: $script"
        echo "script=$script" >> $GITHUB_OUTPUT

    # terraform-nodejs-script
    - uses: aps831/gh-actions/terraform-nodejs-script@feat/deploy
      with:
        working-directory-terraform: ${{ inputs.working-directory-terraform }}
        working-directory-nodejs: ${{ inputs.working-directory-nodejs }}
        terraform-version: ${{ inputs.terraform-version }}
        script: ${{ steps.script.outputs.script }}

    # terraform-values
    - uses: aps831/gh-actions/terraform-values@feat/deploy
      id: bucket
      with:
        working-directory: ${{ inputs.working-directory-terraform }}
        terraform-version: ${{ inputs.terraform-version }}
        output: ${{ inputs.terraform-s3-bucket-name-output }}

    # action-sync-aws-s3-bucket
    - uses: aps831/gh-actions/action-sync-aws-s3-bucket@feat/deploy
      with:
        local-folder-path: ${{ steps.artifact.outputs.artifact-path }}
        remote-bucket-name: ${{ steps.bucket.outputs.output }}
