---
name: Docker Run Container
description: Docker run container
inputs:
  image-name:
    description: Docker image name
    required: true
  working-directory:
    description: Working directory
    required: true
  volumes:
    description: Newline separated list of volumes to attach to build container
    required: true
  env:
    description: Newline separated list of environment variables to inject into build container
    required: true
  commands:
    description: Newline separated list of commands to run inside build container
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        sudo chmod o+rw /var/run/docker.sock
        volumes=$(node ${{ github.action_path }}/volumes.js ${{ github.workspace }} ${{ inputs.working-directory }} $'${{ inputs.volumes }}')
        env=$(node ${{ github.action_path }}/env.js $'${{ inputs.env }}')
        echo "volumes=$volumes"
        echo "env=$env"
        commands="${{ inputs.commands }}"
        while IFS= read -r command || [ -n "$command" ]; do
          if [[ "$command" != "" ]]; then
            echo "Running command: $command"
            docker run --user $(id -u):$(id -g) $volumes -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:$PWD -w $PWD $env ${{ inputs.image-name }} $command
          fi
        done <<< "$commands"
        exit $?
