---
name: Build Basic Project
description: Build basic project
inputs:
  branch-build:
    description: Branch used for build
    required: true
  build-script:
    description: Build script
    required: true
  working-directory:
    description: Working directory
    required: true
  test-results-directory:
    description: Test results directory
    required: true
runs:
  using: "composite"
  steps:
    # git-checkout
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ inputs.branch-build }}

    # create test results directory
    - name: create test results directory
      if: ${{ inputs.test-results-directory != '' }}
      shell: bash
      run: mkdir -p ${{ inputs.working-directory }}/${{ inputs.test-results-directory }}

    # build
    - name: build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.build-script }}

    # output-test-summary
    - uses: aps831/gh-actions/action-output-test-summary@master
      if: ${{ always() && inputs.test-results-directory != '' }}
      with:
        working-directory: ${{ inputs.working-directory }}
        test-result-files: ${{ inputs.test-results-directory }}/*

    # upload-test-results
    - uses: aps831/gh-actions/action-upload-test-results@master
      if: ${{ always() && inputs.test-results-directory != '' }}
      with:
        type: all
        working-directory: ${{ inputs.working-directory }}
        test-result-files: ${{ inputs.test-results-directory }}/*
