---
name: Git Create and Switch Branch
description: Create Git create and switch branch
inputs:
  branch:
    description: Branch to create and switch to
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set +e
        git ls-remote --exit-code --heads origin ${{ inputs.branch }} >/dev/null 2>&1
        EXIT_CODE=$?
        if [[ $EXIT_CODE == '0' ]]; then
          echo "Git branch '${{ inputs.branch }}' exists in the remote repository"
          git fetch
          git switch ${{ inputs.branch }}
        elif [[ $EXIT_CODE == '2' ]]; then
          echo "Git branch '${{ inputs.branch }}' does not exist in the remote repository"
          git checkout -b ${{ inputs.branch }}
        fi
