---
name: Update Terraform Vars
description: Update Terraform vars
inputs:
  tag:
    description: Tag
    required: true
  working-directory:
    description: Working directory
    required: true
  tfvars-filename:
    description: Filename of tfvars files
    required: true
  tfvars-tag-var:
    description: Variable name in tfvars file for tag
    required: true
  tfvars-tag-regex:
    description: Regex of value of tag in tfvars file
    required: true
runs:
  using: "composite"
  steps:
    # find-files
    - uses: aps831/gh-actions/action-find-files@master
      id: files
      with:
        filename: ${{ inputs.tfvars-filename }}
        working-directory: ${{ inputs.working-directory }}

    # update-terraform-vars
    - uses: aps831/gh-actions/action-update-terraform-vars@master
      with:
        paths: ${{ steps.files.outputs.files }}
        tag: ${{ inputs.tag }}
        tag-var: ${{ inputs.tfvars-tag-var }}
        tag-regex: ${{ inputs.tfvars-tag-regex }}

    # git-add-file
    - uses: aps831/gh-actions/git-add-file@master
      with:
        files: ${{ steps.files.outputs.files }}
