---
name: Update Terraform Vars
description: Update Terraform vars
inputs:
  version-identifier:
    description: Version identifier
    required: true
  working-directory:
    description: Working directory
    required: true
  tfvars-filename:
    description: Filename of tfvars files
    required: true
  tfvars-var:
    description: Variable name in tfvars file
    required: true
  tfvars-regex:
    description: Regex of value in tfvars file
    required: true
runs:
  using: "composite"
  steps:
    # find-files
    - uses: aps831/gh-actions/action-find-files@master
      id: files
      with:
        filename: ${{ inputs.tfvars-filename }}
        working-directory: ${{ inputs.working-directory }}

    # update-terraform-vars
    - uses: aps831/gh-actions/action-update-terraform-vars@master
      with:
        paths: ${{ steps.files.outputs.files }}
        version-identifier: ${{ inputs.version-identifier }}
        var: ${{ inputs.tfvars-var }}
        regex: ${{ inputs.tfvars-regex }}

    # git-add-file
    - uses: aps831/gh-actions/git-add-file@master
      with:
        files: ${{ steps.files.outputs.files }}
