---
name: Update Terraform Docs
description: Update Terraform docs
inputs:
  working-directory:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    - name: Render terraform docs
      id: render
      uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # pin@v1.2.0
      with:
        find-dir: ${{ inputs.working-directory }}
        output-file: TERRAFORM.md
        output-method: replace

    - name: Fix .git owner
      shell: bash
      run: sudo chown runner:docker -R .git
