---
name: Update Terraform Docs
description: Update Terraform docs
inputs:
  working-directory:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    - name: Render terraform docs
      id: render
      uses: terraform-docs/gh-actions@7a62208a0090636af2df1b739da46d27fd90bdc6 # pin@v1.1.0
      with:
        find-dir: ${{ inputs.working-directory }}
        output-file: TERRAFORM.md
        output-method: replace

    - name: Fix .git owner
      shell: bash
      run: sudo chown runner:docker -R .git
