---
name: Update Terraform Docs
description: Update Terraform docs
inputs:
  working-directory:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/action-update-terraform-docs@master
      id: update
      with:
        working-directory: ${{ inputs.working-directory }}

    - uses: aps831/gh-actions/git-add-file@master
      with:
        files: ${{ steps.update.outputs.files }}
