---
name: Update Terraform Docs
description: Update Terraform docs
inputs:
  working-directory:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    - name: Render terraform docs
      id: render
      uses: terraform-docs/gh-actions@cca78c27ac9e2b6545debf2ecae9df930fd3461c # pin@v1.2.2
      with:
        find-dir: ${{ inputs.working-directory }}
        output-file: TERRAFORM.md
        output-method: replace

    - name: Fix .git owner
      shell: bash
      run: sudo chown runner:docker -R .git
