---
name: Action Trivy Image Scan
description: Scan Docker image with Trivy
inputs:
  image:
    description: Image name and tag
    required: true
runs:
  using: "composite"
  steps:
    - uses: aquasecurity/trivy-action@d710430a6722f083d3b36b8339ff66b32f22ee55 # pin@v0.19.0
      with:
        image-ref: ${{ inputs.image }}
        format: "table"
        exit-code: "1"
        ignore-unfixed: true
        vuln-type: "os,library"
        severity: "HIGH,CRITICAL"
        output: "trivy-image-results.txt"

    - shell: bash
      if: ${{ always() }}
      run: |
        echo "**Trivy Image '${{ inputs.image }}' Scan Summary**" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        cat trivy-image-results.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
