---
name: Action Build Artifacts Download
description: Download build artifacts
inputs:
  names:
    description: Newline separated list of names of artifacts
    required: true
outputs:
  artifacts-folder:
    description: Artifacts folder
    value: ${{ steps.artifacts-directory.outputs.artifacts-directory }}
runs:
  using: "composite"
  steps:
    - name: create temporary downloads directory
      shell: bash
      id: downloads-directory
      run: echo "downloads-directory=$(mktemp -d)" >> $GITHUB_OUTPUT

    - name: create temporary output directory
      shell: bash
      id: artifacts-directory
      run: echo "artifacts-directory=$(mktemp -d)" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # pin@v3
      with:
        path: "${{ steps.downloads-directory.outputs.downloads-directory }}"

    - name: create temporary output directory
      shell: bash
      run: |
        names="${{ inputs.names }}"
        while IFS= read -r name || [ -n "$name" ]; do
          if [[ -n "$name" && -d "${{ steps.downloads-directory.outputs.downloads-directory }}/$name" ]]; then
            cp -r "${{ steps.downloads-directory.outputs.downloads-directory }}/$name" ${{ steps.artifacts-directory.outputs.artifacts-directory }}
          fi
        done <<< "$names"

    - name: delete temporary downloads directory
      shell: bash
      run: rm -rf ${{ steps.downloads-directory.outputs.downloads-directory }}
