---
name: Set Up SSH
description: Set up SSH
inputs:
  SSH_PRIVATE_KEY:
    description: SSH private key
    required: true
runs:
  using: "composite"
  steps:
    - uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # pin@v0.9.0
      with:
        ssh-private-key: ${{ inputs.SSH_PRIVATE_KEY }}
