---
name: Set Up JDK
description: Set up jdk
inputs:
  java-version:
    description: Java version
    required: false
    default: "17"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # pin@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "adopt"
        cache: "maven"
        server-id: github
        server-username: GITHUB_USER_REF
        server-password: GITHUB_TOKEN_REF
