---
name: Action Latest Release File Read
description: Read latest release file
outputs:
  tag:
    description: Release tag
    value: ${{ steps.tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - id: tag
      shell: bash
      run: |
        if [ -f .latest-release ]; then
          echo "tag=$(cat .latest-release)" >> $GITHUB_OUTPUT
        else
          echo "tag=" >> $GITHUB_OUTPUT
        fi
