---
name: Terraform Value
description: Get value from Terraform
inputs:
  working-directory:
    description: Working directory
    required: true
  terraform-version:
    description: Terraform version
    required: true
  output:
    description: Name of Terraform output
    required: true
outputs:
  value:
    description: Value of Terraform output
    value: ${{ steps.value.outputs.value }}
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/set-up-terraform@master
      with:
        terraform-version: ${{ inputs.terraform-version }}

    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: terraform init

    - id: value
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        value=$(terraform output -raw ${{ inputs.output }})
        echo "value=$value" >> $GITHUB_OUTPUT
