---
name: Set Up Python
description: Set up Python and Poetry
inputs:
  python-version:
    description: Python version
    required: false
    default: latest
  poetry-version:
    description: Poetry version
    required: false
    default: latest
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # pin@v5
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # pin@v4
      with:
        path: .venv*
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - shell: bash
      run: pip install poetry==${{ inputs.poetry-version }}
