---
name: Build Nodejs in Docker Directory Artifact
description: Build Nodejs in Docker directory artifact
inputs:
  branch-build:
    description: Branch used for build
    required: true
  working-directory:
    description: Working directory
    required: true
  dockerfile:
    description: Dockerfile
    required: true
  stage-build:
    description: Stage for building artifact
    required: true
  stage-output:
    description: Stage for outputting artifact
    required: true
  stage-status:
    description: Stage for returning status
    required: true
  output-artifact-directory:
    description: Output directory of artifact
    required: true
  output-sbom-directory:
    description: Output directory of sbom
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
outputs:
  build-artifacts-release-upload-name:
    description: Name of release build artifacts upload
    value: ${{ steps.upload.outputs.name }}
runs:
  using: "composite"
  steps:
    # deprecation warning
    - shell: bash
      run:
        echo "::warning file=build-nodejs-in-docker-directory-artifact,title=DEPRECATED::Update the
        workflow to use v2"

    # git-checkout
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ inputs.branch-build }}

    # docker-build-artifact
    - uses: aps831/gh-actions/docker-build-artifact@master
      with:
        docker-context: ${{ inputs.working-directory }}
        dockerfile: ${{ inputs.working-directory }}/${{ inputs.dockerfile }}
        output-directory: ${{ inputs.working-directory }}
        stage-build: ${{ inputs.stage-build }}
        stage-output: ${{ inputs.stage-output }}
        stage-status: ${{ inputs.stage-status }}

    # zip artifact folder
    - name: zip artifact folder
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        zip -r ${{ inputs.output-artifact-directory }}.zip ${{ inputs.output-artifact-directory }}/*

    # release-artifacts-upload
    - uses: aps831/gh-actions/action-release-artifacts-upload@master
      id: upload
      with:
        description: directory-artifact
        working-directory: ${{ inputs.working-directory }}
        build-files: |
          ${{ inputs.output-artifact-directory }}.zip
          ${{ inputs.output-sbom-directory }}/cyclonedx.json

    # delete zip file
    - name: delete zip file
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        rm ${{ inputs.output-artifact-directory }}.zip
