---
name: Action Convert tgz to zip
description: Convert tgz to zip
inputs:
  filename-tgz:
    description: Filename of tgz archive
    required: true
  strip-components:
    description: Number of components to strip
    required: true
outputs:
  filename-zip:
    description: Filename of zip archive
    value: ${{ steps.filename-zip.outputs.filename-zip }}
runs:
  using: "composite"
  steps:
    - id: tmpdir
      shell: bash
      run: |
        echo "tmpdir=$(mktemp -d)" >> $GITHUB_OUTPUT

    - shell: bash
      working-directory: ${{ steps.tmpdir.outputs.tmpdir }}
      run: |
        tar zxvf ${{ inputs.filename-tgz }} --strip-components=${{ inputs.strip-components }}
        rm ${{ inputs.filename-tgz }}

    - id: filename-zip
      shell: bash
      working-directory: ${{ steps.tmpdir.outputs.tmpdir }}
      run: |
        FILENAME_TAR=$(basename "${{ inputs.filename-tgz }}")
        FILENAME_ZIP="${FILENAME_TAR%.tgz}.zip"
        zip $FILENAME_ZIP *
        echo "filename-zip= ${{ steps.tmpdir.outputs.tmpdir }}/$FILENAME_ZIP" >> $GITHUB_OUTPUT
