---
name: Action Update Nodejs Package Json
description: Update Nodejs package json
inputs:
  working-directory:
    description: Working directory
    required: true
  version:
    description: Version to use in package.json
    required: true
runs:
  using: "composite"
  steps:
    - name: update version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm version --commit-hooks false --git-tag-version false ${{ inputs.version }}
