---
name: Action Update Nodejs Package Json
description: Update Nodejs package json
inputs:
  files:
    description: Newline separated list of files
    required: true
  version:
    description: Version to use in package.json
    required: true
runs:
  using: "composite"
  steps:
    - name: update version
      shell: bash
      run: |
        files="${{ inputs.files }}"
        while IFS= read -r file || [ -n "$file" ]; do
          if [[ -f "$file" ]]; then
            mv "$file" "$file"".bak"
            jq '.version = "${{ inputs.version }}"' "$file"".bak" > "$file"
            rm "$file"".bak"
          fi
        done <<< "$files"
