---
name: Download NPM Package
description: Download NPM package
inputs:
  package-name:
    description: Name of package
    required: true
  package-version:
    description: Version of package
    required: true
  ACCESS_TOKEN:
    description: "Access token"
    required: true
outputs:
  filename-tgz:
    description: Filename of tgz archive
    value: ${{ steps.filename-tgz.outputs.filename-tgz }}
runs:
  using: "composite"
  steps:
    - id: tmpdir
      shell: bash
      run: |
        echo "tmpdir=$(mktemp -d)" >> $GITHUB_OUTPUT

    - id: filename-tgz
      shell: bash
      working-directory: ${{ steps.tmpdir.outputs.tmpdir }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.ACCESS_TOKEN }}
      run: |
        npm pack --pack-destination . ${{ inputs.package-name }}@${{ inputs.package-version }}
        FILES=(*)
        FILENAME_TAR="${FILES[0]}"
        echo "filename-tgz=${{ steps.tmpdir.outputs.tmpdir }}/$FILENAME_TAR" >> $GITHUB_OUTPUT
