---
name: Action Output Test Summary
description: Output test summary
inputs:
  working-directory:
    description: Working directory
    required: true
  test-result-files:
    description: Test result files
    required: true
  component-name:
    description: Component name
    required: false
runs:
  using: "composite"
  steps:
    - name: Header
      shell: bash
      run: |
        if [[ "${{ inputs.component-name }}" != "" ]]; then
          echo "**Test Summary for ${{ inputs.component-name }} on $RUNNER_OS**" >> $GITHUB_STEP_SUMMARY
        else
          echo "**Test Summary on $RUNNER_OS**" >> $GITHUB_STEP_SUMMARY
        fi

    - shell: bash
      id: test-result-files
      run: echo "test-result-files=$(mktemp)" >> $GITHUB_OUTPUT

    - shell: bash
      run:
        echo "${{ inputs.test-result-files }}" > ${{
        steps.test-result-files.outputs.test-result-files }}

    - shell: bash
      run: |
        sed -i -e 's|^.|${{ inputs.working-directory }}/&|' ${{ steps.test-result-files.outputs.test-result-files }}
        sed -i -e 's|^${{ inputs.working-directory }}/!|\!${{ inputs.working-directory }}/|g' ${{ steps.test-result-files.outputs.test-result-files }}

    - shell: bash
      id: working-directory-test-result-files
      run: |
        echo 'working-directory-test-result-files<<EOF' >> $GITHUB_OUTPUT
        cat ${{ steps.test-result-files.outputs.test-result-files }} >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Test summary
      uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # pin@v2
      with:
        paths:
          "${{ steps.working-directory-test-result-files.outputs.working-directory-test-result-files
          }}"
