---
name: Action Build Artifacts Upload
description: Upload build artifacts
inputs:
  description:
    description: Description of artifact
    required: true
  build-files:
    description: Build files
    required: true
outputs:
  name:
    description: Name of build artifacts upload
    value: build-artifacts-${{ steps.description.outputs.name }}
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/action-sanitize-upload-name@master
      id: description
      with:
        name: ${{ inputs.description }}

    - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # pin@v3
      with:
        name: build-artifacts-${{ steps.description.outputs.name }}
        path: ${{ inputs.build-files }}
        retention-days: 1
