---
name: Project Update Terraform
description: Update Terraform project
inputs:
  tag:
    description: Tag
    required: true
  working-directory:
    description: Working directory
    required: true
  templated-files:
    description: Templated files to update with new tag
    required: true
  branch-event:
    description: Branch on which event occurred
    required: true
  branch-update:
    description: Branch to use for creating update
    required: true
  persist-updates:
    description: Persist updates
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    # git checkout
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ inputs.branch-event }}

    # git-create-and-switch-branch
    - uses: aps831/gh-actions/git-create-and-switch-branch@fix/avoid-git-push
      if: ${{ inputs.branch-event != inputs.branch-update }}
      with:
        branch: ${{ inputs.branch-update }}

    # git-configure
    - uses: aps831/gh-actions/git-configure@fix/avoid-git-push

    # update-templated-docs
    - uses: aps831/gh-actions/update-templated-docs@master
      with:
        tag: ${{ inputs.tag }}
        working-directory: ${{ inputs.working-directory }}
        templated-files: ${{ inputs.templated-files }}

    # update-change-log
    - uses: aps831/gh-actions/update-change-log@master
      with:
        tag: ${{ inputs.tag }}
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}

    # update-terraform-docs
    - uses: aps831/gh-actions/update-terraform-docs@master
      with:
        working-directory: ${{ inputs.working-directory }}

    # update-latest-release-file
    - uses: aps831/gh-actions/update-latest-release-file@master
      with:
        tag: ${{ inputs.tag }}

    # git-commit
    - uses: aps831/gh-actions/git-commit@master
      if: ${{ inputs.persist-updates == 'true' }}
      with:
        message: "chore: update for ${{ inputs.tag }} release [skip ci]"

    # git-push
    - uses: aps831/gh-actions/git-push@master
      if: ${{ inputs.persist-updates == 'true' }}
