---
name: AWS Sync S3 bucket
description: AWS Sync S3 bucket
inputs:
  local-folder-path:
    description: Path to local folder
    required: true
  remote-bucket-name:
    description: Bucket name
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        aws s3 sync --delete ${{ inputs.local-folder-path }} s3://${{ inputs.remote-bucket-name }}
