---
name: Docker Pull
description: Pull Docker image
inputs:
  image:
    description: Docker image name
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: docker pull ${{ inputs.image }}
