---
name: Action Create Release Notes
description: Create release notes
inputs:
  current-tag:
    description: Current tag
    required: true
  previous-tag:
    description: Previous tag
    required: true
outputs:
  release-notes-file:
    description: Release notes file
    value: RELEASE.md
runs:
  using: "composite"
  steps:
    - uses: orhun/git-cliff-action@5594a53dc7c8647d85bd3d4da4ca78d3aa3dca4c # pin@v2
      id: git-cliff
      with:
        args: ${{ inputs.previous-tag }}..${{ inputs.current-tag }}
      env:
        OUTPUT: RELEASE.md
