---
name: Action Create Release Notes
description: Create release notes
inputs:
  current-tag:
    description: Current tag
    required: true
  previous-tag:
    description: Previous tag
    required: true
outputs:
  release-notes-file:
    description: Release notes file
    value: RELEASE.md
runs:
  using: "composite"
  steps:
    - uses: orhun/git-cliff-action@1199a3c11df7d17b37c84c2f5daa6d773716177a # pin@v2
      id: git-cliff
      with:
        args: ${{ inputs.previous-tag }}..${{ inputs.current-tag }}
      env:
        OUTPUT: RELEASE.md
