---
name: Project Update Maven Snapshot
description: Update Maven project for snapshot version
inputs:
  pom-version:
    description: Version to use in pom.xml
    required: true
  pom-parent-version:
    description: Parent version to use in pom.xml
    required: true
  tag:
    description: Tag
    required: true
  branch-update:
    description: Branch to use for creating update
    required: true
  working-directory:
    description: Working directory
    required: true
runs:
  using: "composite"
  steps:
    # git-checkout
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ inputs.branch-update }}

    # git-configure
    - uses: aps831/gh-actions/git-configure@master

    # increment pom version
    - name: increment versions
      id: increment-pom
      shell: bash
      run: |
        version=${{ inputs.pom-version }}
        updated="$(echo ${version} | awk -F. -v OFS=. '{$NF += 1 ; print}')"
        echo "updated=${updated}" >> $GITHUB_OUTPUT

    # increment pom-parent version
    - name: increment versions
      id: increment-pom-parent
      shell: bash
      run: |
        version=${{ inputs.pom-parent-version }}
        updated="$(echo ${version} | awk -F. -v OFS=. '{$NF += 1 ; print}')"
        echo "updated=${updated}" >> $GITHUB_OUTPUT

    # update-maven-pom
    - uses: aps831/gh-actions/update-maven-pom@master
      with:
        pom-version: ${{ steps.increment-pom.outputs.updated }}-SNAPSHOT
        pom-parent-version: ${{ steps.increment-pom-parent.outputs.updated }}-SNAPSHOT
        working-directory: ${{ inputs.working-directory }}

    # git-commit
    - uses: aps831/gh-actions/git-commit@master
      with:
        message:
          "chore: update pom version to ${{ steps.increment-pom.outputs.updated }}-SNAPSHOT [skip
          ci]"

    # git-push
    - uses: aps831/gh-actions/git-push@master
