---
name: Action Latest Release File Write
description: Write latest release file
inputs:
  tag:
    description: Release tag
    required: true
outputs:
  filename:
    description: Filename
    value: ".latest-release"
runs:
  using: "composite"
  steps:
    - id: tag
      shell: bash
      run: |
        echo ${{ inputs.tag }} > ".latest-release"
