---
name: Set Up Graalvm Native Image
description: Set up graalvm native image
inputs:
  java-version:
    description: Java version
    required: true
  graalvm-version:
    description: Graalvm version
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: graalvm/setup-graalvm@5393c3d80982e8a7fa61005137824ef53731ff9a # pin@v1
      with:
        version: "${{ inputs.graalvm-version }}"
        java-version: "${{ inputs.java-version }}"
        components: "native-image"
        github-token: ${{ inputs.ACCESS_TOKEN }}

    - uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # pin@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - if: ${{ runner.os == 'Linux' }}
      uses: aps831/gh-actions/install-native-image-linux-dependencies@master

    - if: ${{ runner.os == 'Windows' }}
      uses: aps831/gh-actions/install-native-image-windows-dependencies@master
