---
name: Docker Build Builder Image
description: Docker build builder image
inputs:
  docker-context:
    description: Docker context
    required: true
  dockerfile:
    description: Dockerfile
    required: true
outputs:
  image-name:
    description: Image name
    value: ${{ steps.image-name.outputs.image-name }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: image-name
      run: |
        imageName="builder-image-$(date +"%Y%m%d%H%M%S")"
        echo "image-name=$imageName" >> $GITHUB_OUTPUT

    - shell: bash
      run: |
        USER_ID=$(id -u)
        GROUP_ID=$(getent group docker | cut -d: -f3)
        docker build --build-arg USER_ID=$USER_ID --build-arg GROUP_ID=$GROUP_ID -f ${{ inputs.dockerfile }} ${{ inputs.docker-context }} --build-arg DOCKER_GROUP_ID=$DOCKER_GROUP_ID --progress=plain --sbom=false --provenance=false --tag ${{ steps.image-name.outputs.image-name }}
