---
name: Login AWS
description: AWS login
inputs:
  aws-region:
    description: AWS region
    required: true
  role-to-assume:
    description: Role to assume
    required: true
  role-session-name:
    description: Role session name
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # pin@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-duration-seconds: 1200
        role-session-name: ${{ inputs.role-session-name }}
