---
name: Login to GitHub Container Registry
description: Login to GitHub Container Registry
inputs:
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # pin@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.ACCESS_TOKEN }}
