---
name: Login to GitHub Container Registry
description: Login to GitHub Container Registry
inputs:
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # pin@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.ACCESS_TOKEN }}
