---
name: Login to GitHub Container Registry
description: Login to GitHub Container Registry
inputs:
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # pin@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.ACCESS_TOKEN }}
