---
name: Login to Google Cloud
description: Login to Google Cloud
inputs:
  workload-identity-provider:
    description: Workload identity provider
    required: true
  service-account:
    description: Service account
    required: true
runs:
  using: "composite"
  steps:
    - uses: "google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d" # pin@v1
      with:
        workload_identity_provider: "${{ inputs.workload-identity-provider }}"
        service_account: "${{ inputs.service-account }}"
