---
name: Login to Google Cloud
description: Login to Google Cloud
inputs:
  workload-identity-provider:
    description: Workload identity provider
    required: true
  service-account:
    description: Service account
    required: true
runs:
  using: "composite"
  steps:
    - uses: "google-github-actions/auth@55bd3a7c6e2ae7cf1877fd1ccb9d54c0503c457c" # pin@v1
      with:
        workload_identity_provider: "${{ inputs.workload-identity-provider }}"
        service_account: "${{ inputs.service-account }}"
