---
name: Login to Google Cloud
description: Login to Google Cloud
inputs:
  workload-identity-provider:
    description: Workload identity provider
    required: true
  service-account:
    description: Service account
    required: true
runs:
  using: "composite"
  steps:
    - uses: "google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70" # pin@v1
      with:
        workload_identity_provider: "${{ inputs.workload-identity-provider }}"
        service_account: "${{ inputs.service-account }}"
