---
name: Action Grype SBOM Scan
description: Scan SBOM with Grype
inputs:
  path:
    description: Path of SBOM file
    required: true
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/install-rust-tool@master
      with:
        tool: sarif-fmt

    - uses: anchore/scan-action@1d59d90b47fc11ff8f97822da6c25eec888f81cf # pin@v3
      id: scan
      with:
        sbom: "${{ inputs.path }}"
        output-format: "sarif"
        fail-build: true

    - shell: bash
      if: ${{ always() }}
      run: |
        echo "**Grype SBOM Scan Summary**" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        cat ${{ steps.scan.outputs.sarif }} | sarif-fmt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
