---
name: Action Calculate NPM Github Package Name
description: Calculate NPM Github package name
inputs:
  working-directory:
    description: Working directory
    required: true
outputs:
  package-name:
    description: Package name
    value: ${{ steps.package-name.outputs.package-name }}
runs:
  using: "composite"
  steps:
    - id: package-name
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        packageName=$(jq -r .name package.json)
        echo "package-name=$packageName" >> $GITHUB_OUTPUT
