---
name: Action Update Change Log
description: Update change log
inputs:
  current-tag:
    description: Current tag
    required: true
  start-tag:
    description: Start tag
    required: true
outputs:
  changelog:
    description: Change log file name
    value: CHANGELOG.md
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/install-prettier@master

    - uses: orhun/git-cliff-action@d77b37db2e3f7398432d34b72a12aa3e2ba87e51 # pin@v4
      if: ${{ inputs.start-tag != '' }}
      with:
        args: ${{ inputs.start-tag }}..${{ inputs.current-tag }}
      env:
        OUTPUT: CHANGELOG.md

    - uses: orhun/git-cliff-action@d77b37db2e3f7398432d34b72a12aa3e2ba87e51 # pin@v4
      if: ${{ inputs.start-tag == '' }}
      with:
        args: --tag ${{ inputs.current-tag }}
      env:
        OUTPUT: CHANGELOG.md

    - shell: bash
      run: prettier -w CHANGELOG.md

    - shell: bash
      run: |
        sed -i '1s/^/<!-- markdownlint-disable MD024 -->\n\n/' CHANGELOG.md
