---
name: Action Update Change Log
description: Update change log
inputs:
  current-tag:
    description: Current tag
    required: true
  start-tag:
    description: Start tag
    required: true
outputs:
  changelog:
    description: Change log file name
    value: CHANGELOG.md
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/install-prettier@master

    - uses: orhun/git-cliff-action@14bb67385aaac969efa2f146d137a42bb3b0aa87 # pin@v2
      id: git-cliff
      with:
        args: ${{ inputs.start-tag }}..${{ inputs.current-tag }}
      env:
        OUTPUT: CHANGELOG.md

    - shell: bash
      run: prettier -w CHANGELOG.md

    - shell: bash
      run: |
        sed -i '1s/^/<!-- markdownlint-disable MD024 -->\n\n/' CHANGELOG.md
