---
name: Action Update Change Log
description: Update change log
inputs:
  current-tag:
    description: Current tag
    required: true
  start-tag:
    description: Start tag
    required: true
outputs:
  changelog:
    description: Change log file name
    value: CHANGELOG.md
runs:
  using: "composite"
  steps:
    - uses: orhun/git-cliff-action@90ed560c895459ac2ae450a00604a6ad02a78478 # pin@v2
      id: git-cliff
      with:
        args: ${{ inputs.start-tag }}..${{ inputs.current-tag }}
      env:
        OUTPUT: CHANGELOG.md
