---
name: Action Update Change Log
description: Update change log
inputs:
  current-tag:
    description: Current tag
    required: true
  start-tag:
    description: Start tag
    required: true
outputs:
  changelog:
    description: Change log file name
    value: CHANGELOG.md
runs:
  using: "composite"
  steps:
    - uses: orhun/git-cliff-action@1199a3c11df7d17b37c84c2f5daa6d773716177a # pin@v2
      id: git-cliff
      with:
        args: ${{ inputs.start-tag }}..${{ inputs.current-tag }}
      env:
        OUTPUT: CHANGELOG.md
