---
name: Action Release Artifacts Download
description: Download release artifacts
inputs:
  pattern:
    description: Glob pattern of artifacts to download
    required: true
outputs:
  artifacts-folder:
    description: Artifacts folder
    value: ${{ steps.artifacts-directory.outputs.artifacts-directory }}
runs:
  using: "composite"
  steps:
    - name: create temporary output directory
      shell: bash
      id: artifacts-directory
      run: echo "artifacts-directory=$(mktemp -d)" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # pin@v4
      with:
        path: "${{ steps.artifacts-directory.outputs.artifacts-directory }}"
        pattern: ${{ inputs.pattern }}
