---
name: Action Release Artifacts Download
description: Download release artifacts
inputs:
  pattern:
    description: Glob pattern of artifacts to download
    required: true
outputs:
  artifacts-folder:
    description: Artifacts folder
    value: ${{ steps.artifacts-directory.outputs.artifacts-directory }}
runs:
  using: "composite"
  steps:
    - name: create temporary output directory
      shell: bash
      id: artifacts-directory
      run: echo "artifacts-directory=$(mktemp -d)" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # pin@v4
      with:
        path: "${{ steps.artifacts-directory.outputs.artifacts-directory }}"
        pattern: ${{ inputs.pattern }}
