---
name: Github Release Unpublish
description: Unpublish Github release
inputs:
  tag:
    description: Tag
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # pin@v7
      with:
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const release_id = releases.filter(r => r.tag_name == "${{ inputs.tag }}").map(r => r.id)[0];

          if (release_id != undefined) {
            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release_id
            });
          }
        result-encoding: string
        github-token: ${{ inputs.ACCESS_TOKEN }}

    - uses: aps831/gh-actions/git-delete-tag@master
      with:
        tag: ${{ inputs.tag }}

    - uses: aps831/gh-actions/git-push-delete-tag@master
      with:
        tag: ${{ inputs.tag }}
