---
name: Deploy Branch Validate
description: Deploy branch validate
inputs:
  branch:
    description: Branch to check
    required: true
  branch-check-against:
    description: Branch to check against
    required: true
  max-no-commits:
    description: Maximum number of commits ahead allowed
    required: true
  path:
    description: Path to test for changes
    required: true
outputs:
  not-behind:
    description: Flag to indicate that branch is not behind
    value: ${{ steps.not-behind.outputs.not-behind }}
  not-ahead-by:
    description: Flag to indicate that branch is not ahead by
    value: ${{ steps.not-ahead-by.outputs.not-ahead-by }}
  changes:
    description: Flag to indicate that branch has changes
    value: ${{ steps.changes.outputs.changes }}
runs:
  using: "composite"
  steps:
    - id: not-behind
      uses: aps831/gh-actions/git-branch-not-behind@master
      with:
        branch: ${{ inputs.branch }}
        branch-check-against: ${{ inputs.branch-check-against }}

    - id: not-ahead-by
      uses: aps831/gh-actions/git-branch-not-ahead-by@master
      with:
        branch: ${{ inputs.branch }}
        branch-check-against: ${{ inputs.branch-check-against }}
        max-no-commits: ${{ inputs.max-no-commits }}

    - id: changes
      uses: aps831/gh-actions/git-branch-changes-on-path@master
      with:
        branch: ${{ inputs.branch }}
        branch-check-against: ${{ inputs.branch-check-against }}
        path: ${{ inputs.path }}

    - shell: bash
      run: |
        echo "**Deploy Branch Validate**" >> $GITHUB_STEP_SUMMARY

        echo "" >> $GITHUB_STEP_SUMMARY
        echo "***Comparing branch '${{ inputs.branch }}' against '${{ inputs.branch-check-against }}'***" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        echo "| Key          | Value                                          |" >> $GITHUB_STEP_SUMMARY
        echo "| ------------ | ---------------------------------------------- |" >> $GITHUB_STEP_SUMMARY
        echo "| not-behind   | ${{ steps.not-behind.outputs.not-behind }}     |" >> $GITHUB_STEP_SUMMARY
        echo "| not-ahead-by | ${{ steps.not-ahead-by.outputs.not-ahead-by }} |" >> $GITHUB_STEP_SUMMARY
        echo "| changes      | ${{ steps.changes.outputs.changes }}           |" >> $GITHUB_STEP_SUMMARY

    - shell: bash
      if:
        ${{ steps.not-behind.outputs.not-behind != 'true' || steps.not-ahead-by.outputs.not-ahead-by
        != 'true' || steps.changes.outputs.changes != 'true' }}
      run: |
        echo "::error ::branch validation failed"
        exit 1
