---
name: Set Up Terraform
description: Set up Terraform
inputs:
  terraform-version:
    description: Terraform version
    required: true
runs:
  using: "composite"
  steps:
    - name: Add plugin cache directory to environment
      id: plugin
      shell: bash
      run: |
        echo "plugin-cache-directory=${{ github.workspace }}/.terraform.d/plugin-cache" >> $GITHUB_OUTPUT

    - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # pin@v3.1.2
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Create Terraform Plugin Cache Dir
      shell: bash
      run: mkdir --parents ${{ steps.plugin.outputs.plugin-cache-directory }}

    - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # pin@v4.1.2
      with:
        path: ${{ steps.plugin.outputs.plugin-cache-directory }}
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
