---
name: Set Up Terraform
description: Set up Terraform
inputs:
  terraform-version:
    description: Terraform version
    required: true
runs:
  using: "composite"
  steps:
    - name: Add plugin cache directory to environment
      id: plugin
      shell: bash
      run: |
        echo "plugin-cache-directory=${{ github.workspace }}/.terraform.d/plugin-cache" >> $GITHUB_OUTPUT

    - uses: hashicorp/setup-terraform@97f030cf6dc0b4f5e0da352c7bca9cca34579800 # pin@v3.1.0
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Create Terraform Plugin Cache Dir
      shell: bash
      run: mkdir --parents ${{ steps.plugin.outputs.plugin-cache-directory }}

    - uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # pin@v4.0.2
      with:
        path: ${{ steps.plugin.outputs.plugin-cache-directory }}
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
