---
name: Action Latest Deployment File Read
description: Read latest deployment file
inputs:
  env:
    description: Environment
    required: true
outputs:
  versions:
    description: Versions
    value: # TODO
runs:
  using: "composite"
  steps:
    - id: tag
      shell: bash
      run: |
        if [ -f .latest-deployment-${{ inputs.env }} ]; then
          echo "tag=$(cat .latest-deployment-${{ inputs.env }} | grep ${{ inputs.name }} | awk -F= '{print $2}' )" >> $GITHUB_OUTPUT
        else
          echo "tag=" >> $GITHUB_OUTPUT
        fi

# TODO
# https://gist.github.com/emmanuelnk/13f418d1c1a7eb08ee72ef60a71ca041
# https://stackoverflow.com/questions/1521462/looping-through-the-content-of-a-file-in-bash
