---
name: Build Poetry on Runner Package Artifact
description: Build Poetry on runner package artifact
inputs:
  branch-build:
    description: Branch used for build
    required: true
  working-directory:
    description: Working directory
    required: true
  python-version:
    description: Python version
    required: true
  poetry-version:
    description: Poetry version
    required: true
  build-script:
    description: Build script
    required: true
  output-sbom-directory:
    description: Output directory of sbom
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
outputs:
  build-artifacts-release-upload-name:
    description: Name of release build artifacts upload
    value: ${{ steps.upload.outputs.name }}
runs:
  using: "composite"
  steps:
    # git-checkout
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ inputs.branch-build }}

    # set up python
    - uses: aps831/gh-actions/set-up-python@master
      with:
        python-version: ${{ inputs.python-version }}
        poetry-version: ${{ inputs.poetry-version }}

    # run build script
    - shell: bash
      run: ${{ inputs.build-script }}
      working-directory: ${{ inputs.working-directory }}

    # release-artifacts-upload
    - uses: aps831/gh-actions/action-release-artifacts-upload@master
      id: upload
      with:
        description: cyclonedx-artifact
        working-directory: ${{ inputs.working-directory }}
        build-files: ${{ inputs.output-sbom-directory }}/cyclonedx.json
