---
name: Action Terraform Format
description: Action Terraform format
inputs:
  working-directory:
    description: Working directory
    required: true
  paths:
    description: Newline separated list of paths within working directory
    required: true
runs:
  using: "composite"
  steps:
    - name: Output Terraform format step summary
      shell: bash
      run: echo "**Terraform Format Check Summary**" >> $GITHUB_STEP_SUMMARY

    - name: Terraform format check
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set +e
        paths="${{ inputs.paths }}"
        while IFS= read -r path || [ -n "$path" ]; do
          if [[ -n "$path" && -d "$path" ]]; then

            pushd "$path" > /dev/null 2>&1

            terraform fmt -check -recursive
            exit_code=$?

            echo "### $path" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```text' >> $GITHUB_STEP_SUMMARY

            if [[ "$exit_code" == "0" ]]; then
              echo "Format check passed" >> $GITHUB_STEP_SUMMARY
            else
              echo "Format check failed" >> $GITHUB_STEP_SUMMARY
            fi

            echo '```' >> $GITHUB_STEP_SUMMARY

            popd > /dev/null 2>&1

            if [[ "$exit_code" != "0" ]]; then
              exit $exit_code
            fi

          fi
        done <<< "$paths"
