---
name: Action Latest Deployment File Write
description: Write latest deployment file
inputs:
  version-identifier:
    description: Version identifier
    required: true
  component:
    description: Component
    required: true
  env:
    description: Environment
    required: true
outputs:
  filename:
    description: New or updated filename
    value: .latest-deployment/${{ inputs.env }}/${{ inputs.component }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        mkdir -p .latest-deployment/${{ inputs.env }}
        echo "${{ inputs.version-identifier }}" > .latest-deployment/${{ inputs.env }}/${{ inputs.component }}
