---
name: Docker Build Artifact
description: Docker build artifact
inputs:
  docker-context:
    description: Docker context
    required: true
  dockerfile:
    description: Dockerfile
    required: true
  output-directory:
    description: Output directory
    required: true
  build-args:
    description: Build arguments
    required: true
  secrets:
    description: Secret arguments
    required: true
  stage-build:
    description: Stage for building artifact
    required: true
  stage-output:
    description: Stage for outputting artifact
    required: true
  stage-status:
    description: Stage for returning status
    required: true
runs:
  using: "composite"
  steps:
    # set-up-docker
    - uses: aps831/gh-actions/set-up-docker@master

    # build
    - uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # pin@v3
      with:
        context: ${{ inputs.docker-context }}
        file: ${{ inputs.dockerfile }}
        pull: true
        push: false
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}
        cache-from: type=gha,scope=build
        cache-to: type=gha,scope=build,mode=max
        target: ${{ inputs.stage-build }}

    # output
    - uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # pin@v3
      with:
        context: ${{ inputs.docker-context }}
        file: ${{ inputs.dockerfile }}
        push: false
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}
        cache-from: type=gha,scope=build
        outputs: type=local,dest=${{ inputs.output-directory }}
        target: ${{ inputs.stage-output }}

    # status
    - uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # pin@v3
      with:
        context: ${{ inputs.docker-context }}
        file: ${{ inputs.dockerfile }}
        push: false
        build-args: ${{ inputs.build-args }}
        secrets: ${{ inputs.secrets }}
        cache-from: type=gha,scope=build
        target: ${{ inputs.stage-status }}
