---
name: Action Upload Test Results
description: Upload test results
inputs:
  type:
    description: Type of test results
    required: true
  test-result-files:
    description: Test result files
    required: true
  os-name:
    description: Operating system name
    required: false
  component-name:
    description: Component name
    required: false
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/action-sanitize-upload-name@master
      id: component-name
      with:
        name: ${{ inputs.component-name }}

    - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # pin@v3
      with:
        name: >
          test-reports-type-${{ inputs.type }}${{ inputs.os-name != '' && '-on-' || '' }}${{
          inputs.os-name }}${{ steps.component-name.outputs.name != '' && '-for-' || '' }}${{
          steps.component-name.outputs.name }}
        path: ${{ inputs.test-result-files }}
        retention-days: 3
