---
name: Action Calculate AWS ECR Registry
description: Calculate AWS ECR registry
inputs:
  aws-region:
    description: AWS region
    required: true
outputs:
  registry:
    description: URL for AWS registry
    value: ${{ steps.registry.outputs.registry }}
runs:
  using: "composite"
  steps:
    - shell: bash
      id: registry
      run: |
        account_id=$(aws sts get-caller-identity | jq -r '.Account')
        registry="$account_id.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com"
        echo "registry=$registry" >> $GITHUB_OUTPUT
