---
name: Install xmlstarlet
description: Install xmlstarlet
runs:
  using: "composite"
  steps:
    - id: install-xmlstarlet
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install xmlstarlet
