---
name: Update Latest Release File
description: Update latest release file
inputs:
  tag:
    description: Release tag
    required: true
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/action-latest-release-file-write@master
      id: file
      with:
        tag: ${{ inputs.tag }}

    - uses: aps831/gh-actions/git-add-file@master
      with:
        files: ${{ steps.file.outputs.filename }}
