---
name: Github Issue for Commit
description: Github issue for commit
inputs:
  ACCESS_TOKEN:
    description: Access token
    required: true
outputs:
  issue-number:
    description: Issue number
    value: ${{ steps.result.outputs.result != 'undefined' && steps.result.outputs.result || '' }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # pin@v7
      id: result
      with:
        script: |
          if (context.issue.number) {
            return context.issue.number;
          } else {
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0]?.number;
          }
        result-encoding: string
        github-token: ${{ inputs.ACCESS_TOKEN }}
