---
name: Docker Cosign Verify
description: Docker Cosign verify
inputs:
  image:
    description: Docker image name
    required: true
  COSIGN_PUBLIC_KEY:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # pin@v3.4.0

    - shell: bash
      run: |
        echo "${{ inputs.COSIGN_PUBLIC_KEY }}" > cosign.pub
        cosign verify ${{ inputs.image }} --key cosign.pub -o text
