---
name: Action Grype Image Scan
description: Scan Docker image with Grype
inputs:
  image:
    description: Image name and tag
    required: true
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/install-rust-tool@master
      with:
        tool: sarif-fmt

    - uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # pin@v7
      id: scan
      with:
        image: "${{ inputs.image }}"
        output-format: "sarif"
        fail-build: true

    - shell: bash
      if: ${{ always() }}
      run: |
        echo "**Grype Image '${{ inputs.image }}' Scan Summary**" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        cat ${{ steps.scan.outputs.sarif }} | sarif-fmt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
