---
name: Github No Draft Releases
description: Check Github no draft releases
inputs:
  ACCESS_TOKEN:
    description: Access token
    required: true
outputs:
  no-drafts:
    description: Flag to indicate no draft release
    value: ${{ steps.result.outputs.result }}
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # pin@v7
      id: result
      with:
        script: |
          var release = undefined;
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          if (releases.filter(release => release.draft == true).length == 0) {
            return "true";
          } else {
            return "false";
          }
        result-encoding: string
        github-token: ${{ inputs.ACCESS_TOKEN }}
