---
name: Deployment Branch Instructions
description: Deployment branch instructions
inputs:
  environments:
    description: Newline separated list of environments
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    # message
    - id: message
      shell: bash
      run: |
        environments="${{ inputs.environments }}"
        message="Available deployment commands are:\n"
        while IFS= read -r environment || [ -n "$environment" ]; do
          message=$message" - \`.noop to $environment\` for a noop deployment\n"
          message=$message" - \`.deploy to $environment\` for an actual deployment\n"
        done <<< "$environments"
        echo 'message<<EOF' >> $GITHUB_OUTPUT
        echo -e $message >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    # issue
    - id: issue-number
      uses: aps831/gh-actions/github-issue-for-commit@master
      with:
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}

    # github-add-issue-comment
    - uses: aps831/gh-actions/github-add-issue-comment@master
      with:
        issue-number: ${{ steps.issue-number.outputs.issue-number }}
        comment: ${{ steps.message.outputs.message }}
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}
