---
name: Install Rust Tool
description: Install Rust tool
inputs:
  tool:
    description: Tool including version to install
    required: true
runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@7348990d6a11d92f3e482c9b1bb48cf31ab7f658 # pin@v2
      with:
        tool: ${{ inputs.tool }}
