---
name: Install Rust Tool
description: Install Rust tool
inputs:
  tool:
    description: Tool including version to install
    required: true
runs:
  using: "composite"
  steps:
    - uses: taiki-e/install-action@6c9031f046adb5757845173bcfb8f7fe10599f8f # pin@v2
      with:
        tool: ${{ inputs.tool }}
