---
name: Action Update Terraform Vars
description: Update terraform vars
inputs:
  working-directory:
    description: Working directory
    required: true
  paths:
    description: Paths of tfvars files
    required: true
  update-values:
    description: Newline separated list of pipe separated variable, value regex and value
    required: true
runs:
  using: "composite"
  steps:
    - name: update variable
      shell: bash
      run: |
        paths="${{ inputs.paths }}"
        updates="${{ inputs.update-values }}"
        while IFS= read -r path || [ -n "$path" ]; do
          if [[ -f "$path" ]]; then
            while IFS= read -r update || [ -n "$update" ]; do
              IFS='|' read -r -a array <<< "$update"
              variable="${array[0]}"
              regex="${array[1]}"
              value="${array[2]}"
              sed -i -r "s/^($variable\s+= \")$regex(\")\$/\1$value\2/" "$path"
            done <<< "$updates"
          fi
        done <<< "$paths"
