---
name: Action Update Terraform Vars
description: Update terraform vars
inputs:
  working-directory:
    description: Working directory
    required: true
  paths:
    description: Paths of tfvars files
    required: true
  tag:
    description: Tag
    required: true
  tag-var:
    description: Variable name in tfvars file for tag
    required: true
  tag-regex:
    description: Regex of value of tag in tfvars file
    required: true
runs:
  using: "composite"
  steps:
    - name: update variable
      shell: bash
      run: |
        paths="${{ inputs.paths }}"
        variable="${{ inputs.tag-var }}"
        regex="${{ inputs.tag-regex }}"
        value=${{ inputs.tag }}
        while IFS= read -r path || [ -n "$path" ]; do
          if [[ -f "$path" ]]; then
            sed -i -r "s/^($variable\s+= \")$regex(\")\$/\1$value\2/" "$path"
          fi
        done <<< "$paths"
