---
name: Action Update Terraform Vars
description: Update terraform vars
inputs:
  working-directory:
    description: Working directory
    required: true
  paths:
    description: Paths of tfvars files
    required: true
  version-identifier:
    description: Version identifier
    required: true
  var:
    description: Variable name in tfvars file
    required: true
  regex:
    description: Regex of value in tfvars file
    required: true
runs:
  using: "composite"
  steps:
    - name: update variable
      shell: bash
      run: |
        paths="${{ inputs.paths }}"
        variable="${{ inputs.var }}"
        regex="${{ inputs.regex }}"
        value=${{ inputs.version-identifier }}
        while IFS= read -r path || [ -n "$path" ]; do
          if [[ -f "$path" ]]; then
            sed -i -r "s/^($variable\s+= \")$regex(\")\$/\1$value\2/" "$path"
          fi
        done <<< "$paths"
