---
name: AWS Deploy Release Asset to S3
description: AWS deploy release asset to S3
inputs:
  artifact-name:
    description: Artifact name
    required: true
  release-tag:
    description: Release tag
    required: true
  working-directory:
    description: Working directory
    required: true
  pre-script:
    description: Script to run prior to deployment
    required: true
  post-script:
    description: Script to run after deployment
    required: true
  s3-bucket-secret-name:
    description: Name of secret containing AWS S3 bucket name
    required: true
  aws-region:
    description: AWS region
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    # github-branch-event
    - uses: aps831/gh-actions/github-branch-event@master
      id: branch-event
      with:
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}

    # git checkout event branch
    - uses: aps831/gh-actions/git-checkout@master
      with:
        branch: ${{ steps.branch-event.outputs.branch-event }}

    # action-download-release-artifact
    - uses: aps831/gh-actions/action-download-release-artifact@master
      id: artifact
      with:
        artifact-name: ${{ inputs.artifact-name }}
        release-tag: ${{ inputs.release-tag }}
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}

    - id: artifact-dir
      shell: bash
      run: |
        filename=$(basename "${{ steps.artifact.outputs.artifact-path }}")
        directory=$(dirname "${{ steps.artifact.outputs.artifact-path }}")
        cd "$directory"
        unzip $filename
        artifact_dir="$directory/${filename%.zip}"
        echo "artifact-dir=$artifact_dir" >> $GITHUB_OUTPUT

    # inject artifact directory value into script
    - id: pre-script
      shell: bash
      run: |
        script="${{ inputs.pre-script }}"
        script=${script/\%ARTIFACT_DIR/"${{ steps.artifact-dir.outputs.artifact-dir }}"}
        echo 'script<<EOF' >> $GITHUB_OUTPUT
        echo "$script" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    # run pre-script
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ steps.pre-script.outputs.script }}

    # aws-secret-get
    - uses: aps831/gh-actions/aws-secret-get@master
      id: bucket
      with:
        region: ${{ inputs.aws-region }}
        secret-name: ${{ inputs.s3-bucket-secret-name }}

    # aws-sync-s3-bucket
    - uses: aps831/gh-actions/aws-sync-s3-bucket@master
      with:
        local-folder-path: ${{ steps.artifact-dir.outputs.artifact-dir }}
        remote-bucket-name: ${{ steps.bucket.outputs.value }}

    # inject artifact directory value into script
    - id: post-script
      shell: bash
      run: |
        script="${{ inputs.post-script }}"
        script=${script/\%ARTIFACT_DIR/"${{ steps.artifact-dir.outputs.artifact-dir }}"}
        echo 'script<<EOF' >> $GITHUB_OUTPUT
        echo "$script" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    # run post-script
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ${{ steps.post-script.outputs.script }}
