---
name: Project Update Approve
description: Approve update of project
inputs:
  pull-request-number:
    description: Number of pull request
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: aps831/gh-actions/github-add-issue-comment@master
      with:
        comment: "Merge Approved"
        issue-number: ${{ inputs.pull-request-number }}
        ACCESS_TOKEN: ${{ inputs.ACCESS_TOKEN }}
