---
name: Output and Upload Basic Maven Outputs
description: Output and upload basic maven outputs
inputs:
  working-directory:
    description: Working directory
    required: true
  os-name:
    description: Operating system name
    required: false
  component-name:
    description: Component name
    required: false
runs:
  using: "composite"
  steps:
    # output-test-summary
    - uses: aps831/gh-actions/action-output-test-summary@master
      if: always()
      with:
        working-directory: ${{ inputs.working-directory }}
        component-name: ${{ inputs.component-name }}
        test-result-files: |
          target/surefire-reports/TEST-*.xml
          target/failsafe-reports/TEST-*.xml
          target/surefire-e2e-reports/TEST-*.xml

    # upload-test-results
    - uses: aps831/gh-actions/action-upload-test-results@master
      if: always()
      with:
        type: unit
        working-directory: ${{ inputs.working-directory }}
        test-result-files: |
          target/surefire-reports/TEST-*.xml
        component-name: ${{ inputs.component-name }}
        os-name: ${{ inputs.os-name }}

    # upload-test-results
    - uses: aps831/gh-actions/action-upload-test-results@master
      if: always()
      with:
        type: integration
        working-directory: ${{ inputs.working-directory }}
        test-result-files: |
          target/failsafe-reports/TEST-*.xml
        component-name: ${{ inputs.component-name }}
        os-name: ${{ inputs.os-name }}

    # upload-test-results
    - uses: aps831/gh-actions/action-upload-test-results@master
      if: always()
      with:
        type: e2e
        working-directory: ${{ inputs.working-directory }}
        test-result-files: |
          target/surefire-e2e-reports/TEST-*.xml
        component-name: ${{ inputs.component-name }}
        os-name: ${{ inputs.os-name }}
