---
name: Deployment Candidate Publish
description: Publish deployment candidate
inputs:
  target-owner:
    description: Target owner
    required: true
  target-repo:
    description: Target repository
    required: true
  target-workflow:
    description: Target workflow
    required: true
  target-branch:
    description: Target branch
    required: true
  version-identifier:
    description: Version identifier of deployment candidate
    required: true
  component:
    description: Component
    required: true
  ACCESS_TOKEN:
    description: Access token
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # pin@v7
      env:
        COMPONENT: "${{ inputs.component }}"
      with:
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: "${{ inputs.target-owner }}",
            repo: "${{ inputs.target-repo }}",
            workflow_id: "${{ inputs.target-workflow }}",
            ref: "${{ inputs.target-branch }}",
            inputs: {
              "version-identifier": "${{ inputs.version-identifier }}",
              component: process.env.COMPONENT
            }
          });
        result-encoding: string
        github-token: ${{ inputs.ACCESS_TOKEN }}
